apiVersion: v1
kind: Secret
metadata:
  name: orabank-app-secrets
  namespace: orabank-sms-banking
type: Opaque
stringData:
  # 1. Votre clé JWT générée (88 caractères, 512 bits) - NE PAS CHANGER
  JWT_SECRET: "tJ/D9CzKtuMiatS+PnnG2wHnAsLseU8IgYRIJgRo2hbVgPT1KQ9PS6JJtr3lnLmfeCwSoLu066My9YQ=="
  
  # 2. Clé HMAC pour les webhooks (Legacy / Secours)
  WEBHOOK_SECRET_KEY: "RemplacezParUneTresLongueCleHMACWebhookSecurisee2026!"
  
  # 3. Clé de chiffrement AES (DOIT faire exactement 32 caractères pour AES-256)
  ENCRYPTION_KEY: "01234567890123456789012345678901"
  
  # 4. Clé maîtresse pour les OTP (min 32 caractères)
  OTP_MASTER_SECRET: "ORABANK_MASTER_OTP_SECRET_2026_SECURE_KEY_MIN_32_CHARS"
  
  # 5. Mot de passe Redis (requis par application-prod.yml)
  REDIS_PASSWORD: "VotreMotDePasseRedisCloudProd"
  
  # 6. Identifiants SMS Gateways
  MOOV_SMS_API_KEY: "VotreCleApiMoov"
  MOOV_SMS_API_SECRET: "VotreSecretApiMoov"
  TOGOCEL_SMS_API_KEY: "VotreCleApiTogocel"
  TOGOCEL_SMS_API_SECRET: "VotreSecretApiTogocel"
  
  # 7. Mot de passe Admin (requis par application.yml)
  ADMIN_PASSWORD: "MotDePasseAdminTresSecurise2026!"