# Overlay de production
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: orabank-sms-banking
    count: 5

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: orabank-sms-banking
    spec:
      template:
        spec:
          containers:
            - name: sms-banking
              resources:
                requests:
                  cpu: "1000m"
                  memory: "2Gi"
                limits:
                  cpu: "4000m"
                  memory: "6Gi"
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "prod"
                - name: LOGGING_LEVEL_COM_ORABANK
                  value: "INFO"
                - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
                  value: "health,info,prometheus"

images:
  - name: orabank/sms-banking
    newTag: v1.0.0
