apiVersion: v1
kind: ConfigMap
metadata:
  name: orabank-config
  namespace: orabank-sms-banking
data:
  redis.host: "redis-master.orabank-redis.svc.cluster.local"
  redis.port: "6379"
  sms.provider.url: "https://sms-provider.api.com"
  mobilemoney.provider.url: "https://mobilemoney.provider.com"
  logging.level.root: "INFO"
  logging.level.com.orabank: "DEBUG"
  management.endpoints.web.exposure.include: "health,info,prometheus,metrics,circuitbreakers"
