# Kustomization pour la configuration de base Orabank SMS Banking
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orabank-sms-banking

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - policies.yaml

commonLabels:
  app: orabank-sms-banking
  managed-by: kustomize
