apiVersion: v1
kind: ServiceAccount
metadata:
  name: orabank-sms-banking
  namespace: orabank-sms-banking
  labels:
    app: orabank-sms-banking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orabank-sms-banking-role
  namespace: orabank-sms-banking
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orabank-sms-banking-rolebinding
  namespace: orabank-sms-banking
subjects:
  - kind: ServiceAccount
    name: orabank-sms-banking
    namespace: orabank-sms-banking
roleRef:
  kind: Role
  name: orabank-sms-banking-role
  apiGroup: rbac.authorization.k8s.io
