apiVersion: v1
kind: Secret
metadata:
  name: orabank-db-credentials
  namespace: orabank-sms-banking
type: Opaque
stringData:
  host: "postgres-primary.postgresql.svc.cluster.local"
  database: "orabank_sms"
  username: "orabank_app"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: orabank-webhook-secrets
  namespace: orabank-sms-banking
type: Opaque
stringData:
  hmac-secret: "CHANGE_ME_WITH_SECURE_RANDOM_STRING_MIN_64_CHARS"
  otp-master-secret: "CHANGE_ME_WITH_ANOTHER_SECURE_RANDOM_STRING"
